kind: PersistentVolume
apiVersion: v1
metadata:
  name: config-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/docker/data"
