apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ./docker-compose.yml
      convert
    kompose.version: 1.13.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins-master
  name: jenkins-master
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  - name: "50000"
    port: 50000
    targetPort: 50000
  selector:
    io.kompose.service: jenkins-master
  type: "NodePort"
status:
  loadBalancer: {}
